common: &common
  adapter: postgresql
  username: sales_catalog

development:
  <<: *common
  database: sales_catalog_development

test:
  <<: *common
  database: sales_catalog_test

production:
  <<: *common
  database: myapp_production
