common: &common
  adapter: postgresql
  username: postgres
  password: newPassword

development:
  <<: *common
  database: sales_catalog_development

test:
  <<: *common
  database: sales_catalog_test

production:
  <<: *common
  username: mklttapflfqsx 
  password: qeQSiBqI75DrhwzskkQPhNhWVN
  database: d13lvhu1s00kud

